# Generated by Django 5.2.7 on 2025-01-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(
                choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')],
                default='EFECTIVO',
                max_length=20,
            ),
        ),
    ]
