# Generated by Django 5.2.7 on 2025-10-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('JEFE', 'Jefe'), ('GERENTE', 'Gerente'), ('MECANICO', 'Mecánico'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=20),
        ),
    ]
