# Generated by Django 5.2.7 on 2025-10-28 20:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('estado', models.CharField(choices=[('EN_TALLER', 'En Taller'), ('EN_SERVICIO', 'En Servicio'), ('FINALIZADO', 'Finalizado'), ('MORA', 'En Mora')], default='EN_TALLER', max_length=30)),
                ('ingreso', models.DateField(default=django.utils.timezone.now)),
                ('entrega_estimada', models.DateField(blank=True, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
