# Generated by Django 5.2.7 on 2025-11-24 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='ingreso',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
